# Generated by Django 5.0.1 on 2024-04-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Organizer_Model',
        ),
    ]
