# Generated by Django 5.0.1 on 2024-04-15 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_employee_organizer_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer_model',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='organizer_model',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time'),
        ),
        migrations.AddField(
            model_name='organizer_model',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='organizer_model',
            name='is_RSVP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizer_model',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='organizer_model',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
