# Generated by Django 5.0.1 on 2024-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_name_organizer_model_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer_model',
            name='event_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
