# Generated by Django 4.2 on 2024-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_organizer_model_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer_model',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
