# Generated by Django 4.2 on 2024-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_organizer_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer_model',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date & Time'),
        ),
    ]
